# Generated by Django 4.2.5 on 2023-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todo_user'),
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todos',
            field=models.ManyToManyField(to='todolist.todo'),
        ),
    ]
