# Generated by Django 4.2.5 on 2023-09-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='todos',
        ),
    ]
