# Generated by Django 4.2.5 on 2023-09-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_initial'),
    ]

    operations = [
    ]
