# Generated by Django 4.2.5 on 2023-09-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_created_at'),
        ('todolist', '0003_remove_todo_user'),
    ]

    operations = [
    ]
